/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Color, DoubleSide, FrontSide, MeshPhysicalMaterial } from 'three'
import { clone } from 'three/examples/jsm/utils/SkeletonUtils'
export function Hospital(props) {
  // const { nodes, materials, scene } = useGLTF("/v002/hospital001-webp-v1.glb")
  const glb = useGLTF(`/2022/04/27/v007/hospital007b.glb`)
  const scene = clone(glb.scene)
  scene.traverse((it) => {
    //
    console.log(it)

    if (it.isLight) {
      it.isLight = false
    }
    it.frustumCulled = false
    if (it.geometry) {
      it.castShadow = true
      it.receiveShadow = true

      if (it?.material?.name === 'HospitalGlass') {
        it.castShadow = false
        it.receiveShadow = false
      }

      if (it?.material?.name === 'HospitalTexture003') {
        it.castShadow = false
      }
      // if ((it?.material?.name || "").includes(`HospitalTexture`)) {
      //   it.castShadow = false
      //   it.receiveShadow = false
      // }

      //HospitalTexture003
      // it.geometry.computeVertexNormals()
      it.geometry.computeBoundingSphere()

      // let center = it.geometry.boundingSphere.center.clone()
      // it.geometry.center()
      // it.geometry.computeBoundingSphere()
      // let center2 = it.geometry.boundingSphere.center.clone()

      // center.sub(center2)
      // it.geometry.translate(center.x, center.y, center.z)
      // //
      // it.material = new MeshPhysicalMaterial({ transparent: true })
      // if (it.name === "blinds") {
      //   it.material.side = DoubleSide
      //   it.material.transparent = true
      //   it.castShadow = false
      //   it.material.transmission = 1
      //   it.material.thickness = 1.5
      //   it.material.opacity = 0.5
      // }
      // if (it.name === "floor") {
      //   it.material.metalness = 1
      //   it.material.roughness = 0.23
      // } else {
      //   it.material.color = new Color("#bababa")
      // }
    }
  })
  return (
    <group
      frustumCulled={false}
      onClick={(ev) => {
        console.log(ev)
      }}
      {...props}
      dispose={null}>
      <primitive object={scene}></primitive>
      {/* <group name="Scene">
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={nodes.Plane.material}
          position={[6, 1.5, -13.5]}
          scale={[1, 1, 0.5]}
        />
        <mesh
          name="Plane039"
          castShadow
          receiveShadow
          geometry={nodes.Plane039.geometry}
          material={nodes.Plane039.material}
          position={[10, 1.5, -15.5]}
          scale={[1, 1, 0.5]}
        />
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          position={[5.22, 1.5, -5.02]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane007"
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={nodes.Plane007.material}
          position={[11, 1.5, -15]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Plane021"
          castShadow
          receiveShadow
          geometry={nodes.Plane021.geometry}
          material={nodes.Plane021.material}
          position={[15, 1.5, -15]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Plane011"
          castShadow
          receiveShadow
          geometry={nodes.Plane011.geometry}
          material={nodes.Plane011.material}
          position={[0, 3, -1]}
          scale={[1, 1.5, 1]}
        />
        <mesh name="Plane003" castShadow receiveShadow geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[6, 0, -11]} />
        <mesh
          name="Plane020"
          castShadow
          receiveShadow
          geometry={nodes.Plane020.geometry}
          material={nodes.Plane020.material}
          position={[0, 3, -1]}
          scale={[1, 1.44, 1]}
        />
        <mesh
          name="Plane005"
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={nodes.Plane005.material}
          position={[0, 7.72, -1]}
          scale={[1, 1.44, 1]}
        />
        <mesh
          name="Plane022"
          castShadow
          receiveShadow
          geometry={nodes.Plane022.geometry}
          material={nodes.Plane022.material}
          position={[22, 0, -15]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1.5, 1]}
        />
        <mesh name="floor" castShadow receiveShadow geometry={nodes.floor.geometry} material={nodes.floor.material} scale={[1, 1.5, 1]} />
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
          position={[28, 1.5, -16.25]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Sphere"
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={nodes.Sphere.material}
          position={[10, 3.56, -2.5]}
          scale={0.14}
        />
        <mesh
          name="Plane013"
          castShadow
          receiveShadow
          geometry={nodes.Plane013.geometry}
          material={nodes.Plane013.material}
          position={[32.46, 3, -25.07]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1, 1.44, 1]}
        />
        <mesh
          name="Plane014"
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={nodes.Plane014.material}
          position={[27.69, 3, -20]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1, 1.44, 1]}
        />
        <mesh name="Plane023" castShadow receiveShadow geometry={nodes.Plane023.geometry} material={nodes.Plane023.material} position={[41.92, 3.58, -15.09]} />
        <mesh
          name="Female03001"
          castShadow
          receiveShadow
          geometry={nodes.Female03001.geometry}
          material={materials["Material.003"]}
          position={[2.07, 0.01, -4.23]}
          scale={0.98}
        />
        <mesh
          name="Female03002"
          castShadow
          receiveShadow
          geometry={nodes.Female03002.geometry}
          material={materials["Material.003"]}
          position={[10.99, 0.01, -14.55]}
          scale={0.98}
        />
        <mesh
          name="Female03009"
          castShadow
          receiveShadow
          geometry={nodes.Female03009.geometry}
          material={materials["Material.003"]}
          position={[22.62, 0.01, -9.11]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.98}
        />
        <mesh
          name="Plane024"
          castShadow
          receiveShadow
          geometry={nodes.Plane024.geometry}
          material={nodes.Plane024.material}
          position={[51.97, 3.77, -15.22]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1, 1.33, 1]}
        />
        <mesh name="Plane025" castShadow receiveShadow geometry={nodes.Plane025.geometry} material={nodes.Plane025.material} position={[51.92, 3.58, -15.09]} />
        <mesh
          name="Sphere002"
          castShadow
          receiveShadow
          geometry={nodes.Sphere002.geometry}
          material={nodes.Sphere002.material}
          position={[44.21, 3.54, -15.05]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.14}
        />
        <mesh
          name="Plane026"
          castShadow
          receiveShadow
          geometry={nodes.Plane026.geometry}
          material={nodes.Plane026.material}
          position={[52.36, -5.56, -5.22]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1, 1.33, 1]}
        />
        <mesh
          name="Plane027"
          castShadow
          receiveShadow
          geometry={nodes.Plane027.geometry}
          material={nodes.Plane027.material}
          position={[52.66, -5.56, -7.22]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1, 1.33, 1]}
        />
        <mesh
          name="Tv_mount"
          castShadow
          receiveShadow
          geometry={nodes.Tv_mount.geometry}
          material={nodes.Tv_mount.material}
          position={[51.77, -3.59, -7.88]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[5, 1.78, 0.67]}
        />
        <mesh name="Plane030" castShadow receiveShadow geometry={nodes.Plane030.geometry} material={nodes.Plane030.material} position={[6, 1.5, -15]} />
        <mesh
          name="Sphere003"
          castShadow
          receiveShadow
          geometry={nodes.Sphere003.geometry}
          material={nodes.Sphere003.material}
          position={[36.87, 3.54, -15.05]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.14}
        />
        <mesh name="Plane029" castShadow receiveShadow geometry={nodes.Plane029.geometry} material={nodes.Plane029.material} position={[5.91, 2.29, -16]} />
        <mesh
          name="Cube002"
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={nodes.Cube002.material}
          position={[29.5, 2.8, -15.64]}
          scale={[0.67, 0.75, 1]}
        />
        <mesh
          name="Cube003"
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={nodes.Cube003.material}
          position={[10, 2.8, -1.5]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.67, 0.75, 1]}
        />
        <mesh
          name="Plane032"
          castShadow
          receiveShadow
          geometry={nodes.Plane032.geometry}
          material={nodes.Plane032.material}
          position={[24.55, 4, -13]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Plane033"
          castShadow
          receiveShadow
          geometry={nodes.Plane033.geometry}
          material={nodes.Plane033.material}
          position={[33.94, 4, -15.16]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Plane034"
          castShadow
          receiveShadow
          geometry={nodes.Plane034.geometry}
          material={nodes.Plane034.material}
          position={[24.99, 4.58, -15.04]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Sphere004"
          castShadow
          receiveShadow
          geometry={nodes.Sphere004.geometry}
          material={nodes.Sphere004.material}
          position={[24.92, 3.54, -15.05]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.14}
        />
        <mesh
          name="Plane036"
          castShadow
          receiveShadow
          geometry={nodes.Plane036.geometry}
          material={nodes.Plane036.material}
          position={[19.27, 4, -11.04]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1.44, 0.87]}
        />
        <mesh
          name="Plane037"
          castShadow
          receiveShadow
          geometry={nodes.Plane037.geometry}
          material={nodes.Plane037.material}
          position={[19.31, 4, -14]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1.44, 0.87]}
        />
        <mesh
          name="Plane038"
          castShadow
          receiveShadow
          geometry={nodes.Plane038.geometry}
          material={nodes.Plane038.material}
          position={[10, 0, -18]}
          rotation={[0, -1.57, 0]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Female03003"
          castShadow
          receiveShadow
          geometry={nodes.Female03003.geometry}
          material={materials["Material.003"]}
          position={[18.96, 0.01, -9.05]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.98}
        />
        <mesh
          name="Female03004"
          castShadow
          receiveShadow
          geometry={nodes.Female03004.geometry}
          material={materials["Material.003"]}
          position={[20.98, 0.01, -10.73]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.98}
        />
        <mesh
          name="Female03007"
          castShadow
          receiveShadow
          geometry={nodes.Female03007.geometry}
          material={materials["Material.003"]}
          position={[18.14, 0.01, -14]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.98}
        />
        <mesh
          name="Female03008"
          castShadow
          receiveShadow
          geometry={nodes.Female03008.geometry}
          material={materials["Material.003"]}
          position={[39.16, 0.01, -22.41]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.98}
        />
        <mesh
          name="Plane041"
          castShadow
          receiveShadow
          geometry={nodes.Plane041.geometry}
          material={nodes.Plane041.material}
          position={[20, 3, -10]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Cube004"
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={nodes.Cube004.material}
          position={[29.37, 5.87, -15.25]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.6, 1.5, 0.65]}
        />
        <mesh name="Vert001" castShadow receiveShadow geometry={nodes.Vert001.geometry} material={nodes.Vert001.material} position={[7.66, 0, -0.5]} />
        <mesh
          name="Plane042"
          castShadow
          receiveShadow
          geometry={nodes.Plane042.geometry}
          material={nodes.Plane042.material}
          position={[51.69, 8.78, -13.22]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1, 1.33, 1]}
        />
        <mesh
          name="Plane002"
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={nodes.Plane002.material}
          position={[22, 0, -19.37]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="roof"
          castShadow
          receiveShadow
          geometry={nodes.roof.geometry}
          material={nodes.roof.material}
          position={[40.07, 3.02, -1.3]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.99, 0.93, 4]}
        />
        <mesh
          name="Plane028"
          castShadow
          receiveShadow
          geometry={nodes.Plane028.geometry}
          material={nodes.Plane028.material}
          position={[24, 0, -19.37]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane068"
          castShadow
          receiveShadow
          geometry={nodes.Plane068.geometry}
          material={nodes.Plane068.material}
          position={[11.73, 4.74, -11.92]}
          rotation={[-Math.PI / 2, -0.89, -Math.PI / 2]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane091"
          castShadow
          receiveShadow
          geometry={nodes.Plane091.geometry}
          material={nodes.Plane091.material}
          position={[-2.2, -0.32, -1.57]}
          rotation={[-Math.PI / 2, 0.89, Math.PI / 2]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane117"
          castShadow
          receiveShadow
          geometry={nodes.Plane117.geometry}
          material={nodes.Plane117.material}
          position={[11.73, 9.45, -12.66]}
          rotation={[-Math.PI / 2, -0.89, -Math.PI / 2]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane044"
          castShadow
          receiveShadow
          geometry={nodes.Plane044.geometry}
          material={nodes.Plane044.material}
          position={[32.36, 1.5, -26.05]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane045"
          castShadow
          receiveShadow
          geometry={nodes.Plane045.geometry}
          material={nodes.Plane045.material}
          position={[37.36, 1.5, -17.4]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane069"
          castShadow
          receiveShadow
          geometry={nodes.Plane069.geometry}
          material={nodes.Plane069.material}
          position={[14, 1.5, -14.49]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane079"
          castShadow
          receiveShadow
          geometry={nodes.Plane079.geometry}
          material={nodes.Plane079.material}
          position={[14, 1.5, -16.68]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane092"
          castShadow
          receiveShadow
          geometry={nodes.Plane092.geometry}
          material={nodes.Plane092.material}
          position={[-4.47, -3.56, 1]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane103"
          castShadow
          receiveShadow
          geometry={nodes.Plane103.geometry}
          material={nodes.Plane103.material}
          position={[-4.47, -3.56, 3.19]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane118"
          castShadow
          receiveShadow
          geometry={nodes.Plane118.geometry}
          material={nodes.Plane118.material}
          position={[14, 6.2, -15.23]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane130"
          castShadow
          receiveShadow
          geometry={nodes.Plane130.geometry}
          material={nodes.Plane130.material}
          position={[14, 6.2, -17.42]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane046"
          castShadow
          receiveShadow
          geometry={nodes.Plane046.geometry}
          material={nodes.Plane046.material}
          position={[24.04, 3, -14]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane047"
          castShadow
          receiveShadow
          geometry={nodes.Plane047.geometry}
          material={nodes.Plane047.material}
          position={[37.36, 1.5, -22.37]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane051"
          castShadow
          receiveShadow
          geometry={nodes.Plane051.geometry}
          material={nodes.Plane051.material}
          position={[53.52, 3.77, -16.16]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1, 1.33, 1]}
        />
        <mesh
          name="Plane052"
          castShadow
          receiveShadow
          geometry={nodes.Plane052.geometry}
          material={nodes.Plane052.material}
          position={[50.67, 8.23, -14.95]}
          scale={[1, 1.33, 1]}
        />
        <mesh name="Circle" castShadow receiveShadow geometry={nodes.Circle.geometry} material={nodes.Circle.material} position={[19.4, 0.62, -9.65]} />
        <mesh
          name="Circle003"
          castShadow
          receiveShadow
          geometry={nodes.Circle003.geometry}
          material={nodes.Circle003.material}
          position={[19.4, 0.62, -11.84]}
        />
        <mesh
          name="Circle006"
          castShadow
          receiveShadow
          geometry={nodes.Circle006.geometry}
          material={nodes.Circle006.material}
          position={[-9.88, -4.44, -3.84]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Circle009"
          castShadow
          receiveShadow
          geometry={nodes.Circle009.geometry}
          material={nodes.Circle009.material}
          position={[-9.88, -4.44, -1.64]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Circle012"
          castShadow
          receiveShadow
          geometry={nodes.Circle012.geometry}
          material={nodes.Circle012.material}
          position={[19.4, 5.32, -10.4]}
        />
        <mesh
          name="Circle015"
          castShadow
          receiveShadow
          geometry={nodes.Circle015.geometry}
          material={nodes.Circle015.material}
          position={[19.4, 5.32, -12.59]}
        />
        <mesh
          name="Plane073"
          castShadow
          receiveShadow
          geometry={nodes.Plane073.geometry}
          material={nodes.Plane073.material}
          position={[10.9, 5.05, -9.64]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane082"
          castShadow
          receiveShadow
          geometry={nodes.Plane082.geometry}
          material={nodes.Plane082.material}
          position={[10.9, 5.05, -11.84]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane095"
          castShadow
          receiveShadow
          geometry={nodes.Plane095.geometry}
          material={nodes.Plane095.material}
          position={[-1.37, -0.01, -3.84]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane106"
          castShadow
          receiveShadow
          geometry={nodes.Plane106.geometry}
          material={nodes.Plane106.material}
          position={[-1.37, -0.01, -1.65]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane122"
          castShadow
          receiveShadow
          geometry={nodes.Plane122.geometry}
          material={nodes.Plane122.material}
          position={[10.9, 9.76, -10.39]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane133"
          castShadow
          receiveShadow
          geometry={nodes.Plane133.geometry}
          material={nodes.Plane133.material}
          position={[10.9, 9.76, -12.58]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane053"
          castShadow
          receiveShadow
          geometry={nodes.Plane053.geometry}
          material={nodes.Plane053.material}
          position={[50.67, 3.77, -18.24]}
          scale={[1, 1.33, 1]}
        />
        <mesh
          name="Plane054"
          castShadow
          receiveShadow
          geometry={nodes.Plane054.geometry}
          material={nodes.Plane054.material}
          position={[48.67, 8.78, -14.81]}
          scale={[1, 1.33, 1]}
        />
        <mesh
          name="Plane055"
          castShadow
          receiveShadow
          geometry={nodes.Plane055.geometry}
          material={nodes.Plane055.material}
          position={[55.08, 1.5, -15.25]}
          rotation={[0, -1.57, 0]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane056"
          castShadow
          receiveShadow
          geometry={nodes.Plane056.geometry}
          material={nodes.Plane056.material}
          position={[63.94, 1.5, -8.22]}
          rotation={[0, -1.57, 0]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane070"
          castShadow
          receiveShadow
          geometry={nodes.Plane070.geometry}
          material={nodes.Plane070.material}
          position={[19.4, 0.15, -11.42]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane058"
          castShadow
          receiveShadow
          geometry={nodes.Plane058.geometry}
          material={nodes.Plane058.material}
          position={[9.85, 5.17, -9.64]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane071"
          castShadow
          receiveShadow
          geometry={nodes.Plane071.geometry}
          material={nodes.Plane071.material}
          position={[19.4, 0.15, -9.64]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane083"
          castShadow
          receiveShadow
          geometry={nodes.Plane083.geometry}
          material={nodes.Plane083.material}
          position={[19.4, 0.15, -13.61]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane085"
          castShadow
          receiveShadow
          geometry={nodes.Plane085.geometry}
          material={nodes.Plane085.material}
          position={[9.85, 5.17, -11.84]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane087"
          castShadow
          receiveShadow
          geometry={nodes.Plane087.geometry}
          material={nodes.Plane087.material}
          position={[19.4, 0.15, -11.84]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane097"
          castShadow
          receiveShadow
          geometry={nodes.Plane097.geometry}
          material={nodes.Plane097.material}
          position={[-9.88, -4.92, -2.07]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane099"
          castShadow
          receiveShadow
          geometry={nodes.Plane099.geometry}
          material={nodes.Plane099.material}
          position={[-0.32, 0.1, -3.84]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane101"
          castShadow
          receiveShadow
          geometry={nodes.Plane101.geometry}
          material={nodes.Plane101.material}
          position={[-9.88, -4.92, -3.84]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane107"
          castShadow
          receiveShadow
          geometry={nodes.Plane107.geometry}
          material={nodes.Plane107.material}
          position={[-9.88, -4.92, 0.12]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane109"
          castShadow
          receiveShadow
          geometry={nodes.Plane109.geometry}
          material={nodes.Plane109.material}
          position={[-0.32, 0.1, -1.65]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane111"
          castShadow
          receiveShadow
          geometry={nodes.Plane111.geometry}
          material={nodes.Plane111.material}
          position={[-9.88, -4.92, -1.65]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane124"
          castShadow
          receiveShadow
          geometry={nodes.Plane124.geometry}
          material={nodes.Plane124.material}
          position={[19.4, 4.85, -12.16]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane126"
          castShadow
          receiveShadow
          geometry={nodes.Plane126.geometry}
          material={nodes.Plane126.material}
          position={[9.85, 9.87, -10.39]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane128"
          castShadow
          receiveShadow
          geometry={nodes.Plane128.geometry}
          material={nodes.Plane128.material}
          position={[19.4, 4.85, -10.39]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane134"
          castShadow
          receiveShadow
          geometry={nodes.Plane134.geometry}
          material={nodes.Plane134.material}
          position={[19.4, 4.85, -14.35]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane136"
          castShadow
          receiveShadow
          geometry={nodes.Plane136.geometry}
          material={nodes.Plane136.material}
          position={[9.85, 9.87, -12.58]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane138"
          castShadow
          receiveShadow
          geometry={nodes.Plane138.geometry}
          material={nodes.Plane138.material}
          position={[19.4, 4.85, -12.58]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane057"
          castShadow
          receiveShadow
          geometry={nodes.Plane057.geometry}
          material={nodes.Plane057.material}
          position={[51.61, 3.77, -16.16]}
          scale={[1, 1.33, 1]}
        />
        <mesh
          name="Plane088"
          castShadow
          receiveShadow
          geometry={nodes.Plane088.geometry}
          material={nodes.Plane088.material}
          position={[14, 1.5, -9.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -2]}
        />
        <mesh
          name="Plane112"
          castShadow
          receiveShadow
          geometry={nodes.Plane112.geometry}
          material={nodes.Plane112.material}
          position={[-4.47, -3.56, -4.33]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-1, -1, -2]}
        />
        <mesh
          name="Plane139"
          castShadow
          receiveShadow
          geometry={nodes.Plane139.geometry}
          material={nodes.Plane139.material}
          position={[14, 6.2, -9.91]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -2]}
        />
        <mesh
          name="Cube006"
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={nodes.Cube006.material}
          position={[22.5, 2.8, -15.64]}
          scale={[0.67, 0.75, 1]}
        />
        <mesh
          name="Cube005"
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={nodes.Cube005.material}
          position={[24.83, 5.87, -15.25]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.6, 1.5, 0.65]}
        />
        <mesh
          name="Plane059"
          castShadow
          receiveShadow
          geometry={nodes.Plane059.geometry}
          material={nodes.Plane059.material}
          position={[64.94, 1.5, -9.22]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane060"
          castShadow
          receiveShadow
          geometry={nodes.Plane060.geometry}
          material={nodes.Plane060.material}
          position={[53.64, 3, -11.8]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane061"
          castShadow
          receiveShadow
          geometry={nodes.Plane061.geometry}
          material={nodes.Plane061.material}
          position={[54, 1.5, -18.25]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane064"
          castShadow
          receiveShadow
          geometry={nodes.Plane064.geometry}
          material={nodes.Plane064.material}
          position={[38.73, 3, -23]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane049"
          castShadow
          receiveShadow
          geometry={nodes.Plane049.geometry}
          material={nodes.Plane049.material}
          position={[43.1, 1.5, -21.37]}
          rotation={[0, -1.57, 0]}
          scale={[1, 1.5, 1]}
        />
        <mesh name="Plane065" castShadow receiveShadow geometry={nodes.Plane065.geometry} material={nodes.Plane065.material} position={[40.1, 3, -21.37]} />
        <mesh name="Plane066" castShadow receiveShadow geometry={nodes.Plane066.geometry} material={nodes.Plane066.material} position={[40.1, 3, -23.37]} />
        <mesh
          name="Plane062"
          castShadow
          receiveShadow
          geometry={nodes.Plane062.geometry}
          material={nodes.Plane062.material}
          position={[32.04, 3, -20.89]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane063"
          castShadow
          receiveShadow
          geometry={nodes.Plane063.geometry}
          material={nodes.Plane063.material}
          position={[11, 4.5, -15]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Plane067"
          castShadow
          receiveShadow
          geometry={nodes.Plane067.geometry}
          material={nodes.Plane067.material}
          position={[6, 3, -15]}
          scale={[1, 1.5, 1]}
        />
        <mesh name="Cube008" castShadow receiveShadow geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[12.67, 0.06, -7.14]} />
        <mesh name="Cube009" castShadow receiveShadow geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[15.97, 0.06, -7.14]} />
        <mesh
          name="Plane076"
          castShadow
          receiveShadow
          geometry={nodes.Plane076.geometry}
          material={nodes.Plane076.material}
          position={[19.11, -4.68, -16.16]}
          scale={[1, 1.33, 1]}
        />
        <mesh
          name="Cube011"
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={nodes.Cube011.material}
          position={[24.46, 5.87, -10.53]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.6, 1.5, 0.65]}
        />
        <mesh
          name="Cube007"
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={nodes.Cube007.material}
          position={[24.08, 5.87, -10.16]}
          rotation={[0, -1.57, 0]}
          scale={[0.6, 1.5, 0.65]}
        />
        <mesh
          name="Cube010"
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={nodes.Cube010.material}
          position={[16.85, 5.87, -10.16]}
          rotation={[0, -1.57, 0]}
          scale={[0.6, 1.5, 0.65]}
        />
        <mesh
          name="floor001"
          castShadow
          receiveShadow
          geometry={nodes.floor001.geometry}
          material={nodes.floor001.material}
          position={[0, 0, 2]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane113"
          castShadow
          receiveShadow
          geometry={nodes.Plane113.geometry}
          material={nodes.Plane113.material}
          position={[39.1, 1.5, -35.37]}
          rotation={[0, -1.57, 0]}
          scale={[1, 1.5, 1]}
        />
        <mesh
          name="Plane004"
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={nodes.Plane004.material}
          position={[6.96, 4, -1.09]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Plane119"
          castShadow
          receiveShadow
          geometry={nodes.Plane119.geometry}
          material={nodes.Plane119.material}
          position={[6.96, 8.72, -1.09]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Cube012"
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={nodes.Cube012.material}
          position={[9.86, 5.87, -2.34]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.6, 1.5, 0.65]}
        />
        <mesh
          name="Plane009"
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={nodes.Plane009.material}
          position={[40.07, 1.4, -0.82]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1, 0.93, 4]}
        />
        <mesh name="blinds" castShadow receiveShadow geometry={nodes.blinds.geometry} material={nodes.blinds.material} position={[49.19, 5.8, -0.4]} />
        <mesh
          name="Plane019"
          castShadow
          receiveShadow
          geometry={nodes.Plane019.geometry}
          material={nodes.Plane019.material}
          position={[18.96, 1.4, 0.18]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1, 0.93, 4]}
        />
        <mesh name="Vert" castShadow receiveShadow geometry={nodes.Vert.geometry} material={nodes.Vert.material} position={[7.66, 0, -0.5]} />
        <mesh name="glass" castShadow receiveShadow geometry={nodes.glass.geometry} material={nodes.glass.material} position={[2.51, 3, 0.28]} />
        <mesh
          name="Plane043"
          castShadow
          receiveShadow
          geometry={nodes.Plane043.geometry}
          material={nodes.Plane043.material}
          position={[40.07, 3.02, -1.3]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1, 0.93, 4]}
        />
        <mesh
          name="Plane010"
          castShadow
          receiveShadow
          geometry={nodes.Plane010.geometry}
          material={nodes.Plane010.material}
          position={[14, 1.35, -14.21]}
          scale={[1, 0.9, 2]}
        />
        <mesh
          name="Plane089"
          castShadow
          receiveShadow
          geometry={nodes.Plane089.geometry}
          material={nodes.Plane089.material}
          position={[-4.47, -3.71, 0.73]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 0.9, 2]}
        />
        <mesh
          name="Plane016"
          castShadow
          receiveShadow
          geometry={nodes.Plane016.geometry}
          material={nodes.Plane016.material}
          position={[14, 1.5, -14.49]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane078"
          castShadow
          receiveShadow
          geometry={nodes.Plane078.geometry}
          material={nodes.Plane078.material}
          position={[14, 1.5, -16.68]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane090"
          castShadow
          receiveShadow
          geometry={nodes.Plane090.geometry}
          material={nodes.Plane090.material}
          position={[-4.47, -3.56, 1]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane102"
          castShadow
          receiveShadow
          geometry={nodes.Plane102.geometry}
          material={nodes.Plane102.material}
          position={[-4.47, -3.56, 3.19]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane040"
          castShadow
          receiveShadow
          geometry={nodes.Plane040.geometry}
          material={nodes.Plane040.material}
          position={[14, 6.2, -15.23]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane129"
          castShadow
          receiveShadow
          geometry={nodes.Plane129.geometry}
          material={nodes.Plane129.material}
          position={[14, 6.2, -17.42]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Circle002"
          castShadow
          receiveShadow
          geometry={nodes.Circle002.geometry}
          material={materials.glass}
          position={[14.69, 3.08, -11.42]}
          scale={[1, 1, 0]}
        />
        <mesh
          name="Circle001"
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials.glass}
          position={[14.69, 3.08, -9.65]}
          scale={[1, 1, 0]}
        />
        <mesh
          name="Circle004"
          castShadow
          receiveShadow
          geometry={nodes.Circle004.geometry}
          material={materials.glass}
          position={[14.69, 3.08, -13.61]}
          scale={[1, 1, 0]}
        />
        <mesh
          name="Circle005"
          castShadow
          receiveShadow
          geometry={nodes.Circle005.geometry}
          material={materials.glass}
          position={[14.69, 3.08, -11.84]}
          scale={[1, 1, 0]}
        />
        <mesh
          name="Circle007"
          castShadow
          receiveShadow
          geometry={nodes.Circle007.geometry}
          material={materials.glass}
          position={[-5.16, -1.99, -2.07]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 0]}
        />
        <mesh
          name="Circle008"
          castShadow
          receiveShadow
          geometry={nodes.Circle008.geometry}
          material={materials.glass}
          position={[-5.16, -1.99, -3.84]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 0]}
        />
        <mesh
          name="Circle010"
          castShadow
          receiveShadow
          geometry={nodes.Circle010.geometry}
          material={materials.glass}
          position={[-5.16, -1.99, 0.12]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 0]}
        />
        <mesh
          name="Circle011"
          castShadow
          receiveShadow
          geometry={nodes.Circle011.geometry}
          material={materials.glass}
          position={[-5.16, -1.99, -1.64]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 0]}
        />
        <mesh
          name="Circle013"
          castShadow
          receiveShadow
          geometry={nodes.Circle013.geometry}
          material={materials.glass}
          position={[14.69, 7.78, -12.16]}
          scale={[1, 1, 0]}
        />
        <mesh
          name="Circle014"
          castShadow
          receiveShadow
          geometry={nodes.Circle014.geometry}
          material={materials.glass}
          position={[14.69, 7.78, -10.4]}
          scale={[1, 1, 0]}
        />
        <mesh
          name="Circle016"
          castShadow
          receiveShadow
          geometry={nodes.Circle016.geometry}
          material={materials.glass}
          position={[14.69, 7.78, -14.36]}
          scale={[1, 1, 0]}
        />
        <mesh
          name="Circle017"
          castShadow
          receiveShadow
          geometry={nodes.Circle017.geometry}
          material={materials.glass}
          position={[14.69, 7.78, -12.59]}
          scale={[1, 1, 0]}
        />
        <mesh
          name="Plane074"
          castShadow
          receiveShadow
          geometry={nodes.Plane074.geometry}
          material={nodes.Plane074.material}
          position={[17.76, 0.21, -9.64]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane080"
          castShadow
          receiveShadow
          geometry={nodes.Plane080.geometry}
          material={nodes.Plane080.material}
          position={[17.76, 0.21, -11.84]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane093"
          castShadow
          receiveShadow
          geometry={nodes.Plane093.geometry}
          material={nodes.Plane093.material}
          position={[-8.23, -4.86, -3.84]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane104"
          castShadow
          receiveShadow
          geometry={nodes.Plane104.geometry}
          material={nodes.Plane104.material}
          position={[-8.23, -4.86, -1.65]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane120"
          castShadow
          receiveShadow
          geometry={nodes.Plane120.geometry}
          material={nodes.Plane120.material}
          position={[17.76, 4.91, -10.39]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane131"
          castShadow
          receiveShadow
          geometry={nodes.Plane131.geometry}
          material={nodes.Plane131.material}
          position={[17.76, 4.91, -12.58]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane075"
          castShadow
          receiveShadow
          geometry={nodes.Plane075.geometry}
          material={nodes.Plane075.material}
          position={[18.41, 0.15, -9.64]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane081"
          castShadow
          receiveShadow
          geometry={nodes.Plane081.geometry}
          material={nodes.Plane081.material}
          position={[18.41, 0.15, -11.84]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane094"
          castShadow
          receiveShadow
          geometry={nodes.Plane094.geometry}
          material={nodes.Plane094.material}
          position={[-8.88, -4.92, -3.84]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane105"
          castShadow
          receiveShadow
          geometry={nodes.Plane105.geometry}
          material={nodes.Plane105.material}
          position={[-8.88, -4.92, -1.65]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane121"
          castShadow
          receiveShadow
          geometry={nodes.Plane121.geometry}
          material={nodes.Plane121.material}
          position={[18.41, 4.85, -10.39]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane132"
          castShadow
          receiveShadow
          geometry={nodes.Plane132.geometry}
          material={nodes.Plane132.material}
          position={[18.41, 4.85, -12.58]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane015"
          castShadow
          receiveShadow
          geometry={nodes.Plane015.geometry}
          material={nodes.Plane015.material}
          position={[14, 1.5, -14.21]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane096"
          castShadow
          receiveShadow
          geometry={nodes.Plane096.geometry}
          material={nodes.Plane096.material}
          position={[-4.47, -3.56, 0.73]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane123"
          castShadow
          receiveShadow
          geometry={nodes.Plane123.geometry}
          material={nodes.Plane123.material}
          position={[14, 6.2, -14.96]}
          scale={[1, 1, 2]}
        />
        <mesh
          name="Plane072"
          castShadow
          receiveShadow
          geometry={nodes.Plane072.geometry}
          material={nodes.Plane072.material}
          position={[19.06, 0.15, -9.64]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane084"
          castShadow
          receiveShadow
          geometry={nodes.Plane084.geometry}
          material={nodes.Plane084.material}
          position={[19.06, 0.15, -11.84]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane098"
          castShadow
          receiveShadow
          geometry={nodes.Plane098.geometry}
          material={nodes.Plane098.material}
          position={[-9.54, -4.92, -3.84]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane108"
          castShadow
          receiveShadow
          geometry={nodes.Plane108.geometry}
          material={nodes.Plane108.material}
          position={[-9.54, -4.92, -1.65]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane125"
          castShadow
          receiveShadow
          geometry={nodes.Plane125.geometry}
          material={nodes.Plane125.material}
          position={[19.06, 4.85, -10.39]}
          scale={[1, 1, 2.1]}
        />
        <mesh
          name="Plane135"
          castShadow
          receiveShadow
          geometry={nodes.Plane135.geometry}
          material={nodes.Plane135.material}
          position={[19.06, 4.85, -12.58]}
          scale={[1, 1, 2.1]}
        />
        <mesh name="Plane077" castShadow receiveShadow geometry={nodes.Plane077.geometry} material={nodes.Plane077.material} position={[10, 5.23, -11.35]} />
        <mesh name="Plane086" castShadow receiveShadow geometry={nodes.Plane086.geometry} material={nodes.Plane086.material} position={[10, 5.23, -13.54]} />
        <mesh
          name="Plane100"
          castShadow
          receiveShadow
          geometry={nodes.Plane100.geometry}
          material={nodes.Plane100.material}
          position={[-0.47, 0.17, -2.13]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Plane110"
          castShadow
          receiveShadow
          geometry={nodes.Plane110.geometry}
          material={nodes.Plane110.material}
          position={[-0.47, 0.17, 0.06]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh name="Plane127" castShadow receiveShadow geometry={nodes.Plane127.geometry} material={nodes.Plane127.material} position={[10, 9.94, -12.1]} />
        <mesh name="Plane137" castShadow receiveShadow geometry={nodes.Plane137.geometry} material={nodes.Plane137.material} position={[10, 9.94, -14.29]} />
        <mesh
          name="Female03006"
          castShadow
          receiveShadow
          geometry={nodes.Female03006.geometry}
          material={materials["Material.003"]}
          position={[-5.56, 0.01, -12.75]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Female03005"
          castShadow
          receiveShadow
          geometry={nodes.Female03005.geometry}
          material={materials["Material.003"]}
          position={[12.56, 0.01, -6.51]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.98}
        />
      </group> */}
    </group>
  )
}
